#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# プロンプト
# master	branch
# ↑		pushしてないコミットあり
# *			add していないファイルあり
# x
# +			コミットしていないファイルあり
# ■		git 管理外のファイルあり
# →

# Customize to your needs...

# gtags
# export GTAGSLIBPATH=/usr/include

# for qmk_firmware
export GTAGSLIBPATH=/usr/local/Cellar/avr-gcc/7.3.0/avr/include
# :/usr/local/Cellar/avr-gcc/7.3.0/avr/include/sys\
# :/usr/local/Cellar/avr-gcc/7.3.0/avr/include/avr\
# :/usr/local/Cellar/avr-gcc/7.3.0/avr/include/util\

# editor
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# represent file path in title bar
precmd() {eval 'echo -ne "\033]0;${PWD/#$HOME/~}\007"'}

# my zip command
# zip DIR-NAME
function zzip () {
    dir=$1
    d=`echo $dir | sed -e 's/\/$//'`
    \zip -r $d.zip $d
    if [ "$?" -eq 0 ]; then
        echo
        echo -n "  Zipped to: "
        ls -d $PWD/{*,.*} | grep $d.zip
    fi
}
alias zip=zzip

# command alias
# (to invoke original command, use "\command")
#
alias emacs='/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.4/bin/emacs-26.1'
alias rm='/usr/local/bin/trash -F'

# buffer clear on iTerm2
alias cls='printf "\e]50;ClearScrollback\a"'

PATH=$HOME/bin:$PATH      # my script or tools

# # zaw
# source /Users/g/git-clone/zaw/zaw.zsh

# autoload -Uz chpwd_recent_dirs cdr add-zsh-hook is-at-least
# if is-at-least 4.3.10; then
# add-zsh-hook chpwd chpwd_recent_dirs
# zstyle ':chpwd:*' recent-dirs-max 5000
# zstyle ':chpwd:*' recent-dirs-default yes
# fi

# zstyle ':filter-select' case-insensitive yes
# bindkey '^xb'  zaw-cdr
# bindkey '^x^r' zaw-history


# # history by peco
# function peco-history-selection() {
#     # BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
#     BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | fzy`
#     CURSOR=$#BUFFER
#     zle reset-prompt
# }

# rga: rip-grep all wigh fzf
rga-fzf() {
	RG_PREFIX="rga --files-with-matches"
	local file
	file="$(
		FZF_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
			fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
				--phony -q "$1" \
				--bind "change:reload:$RG_PREFIX {q}" \
				--preview-window="70%:wrap"
	)" &&
	echo "opening $file" &&
	xdg-open "$file"
}

# zle -N peco-history-selection
# bindkey '^r' peco-history-selection

function history-fzy() {
  BUFFER=$(history | sort -r -k 1,2 | awk '!a[$0]++{$1=""; print}' | fzy --query "$LBUFFER")
  CURSOR=$#BUFFER

  zle reset-prompt
}

zle -N history-fzy
bindkey '^r' history-fzy



# docker completion
if [ -e ~/.zsh/completions ]; then
  fpath=(~/.zsh/completions $fpath)
fi

autoload -U compinit
compinit


# heroku autocomplete setup
HEROKU_AC_ZSH_SETUP_PATH=/Users/g/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
source /Users/g/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# flutter sdk
export PATH="$PATH:/Users/g/tmp/flutter/bin"

# meld
alias meld='/Applications/Meld.app/Contents/MacOS/Meld'

# wine
alias wine='/Applications/Wine\ Stable.app/Contents/MacOS/wine'


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
